/*
verilator --cc --exe --build -j 0 --top-module itch_parser \
    rtl/msg_pkg.sv rtl/skid_buffer.sv rtl/itch_parser.sv \
    tb/parser/tb_itch_parser.cpp
./obj_dir/Vitch_parser
*/

#include "Vitch_parser.h" // class generated by Verilator
#include <verilated.h> // runtime thing for Verilator
#include <cstdio>
#include <cstdint>

#include "../shared/itch_messages.h"

static constexpr int RESET_CYCLES = 5; // constexpr is C++ for eval this at compile time, not run time
static constexpr int TDATA_WORDS = 12; // 384b = 12 words * 32 bits

static void tick(Vitch_parser* dut) // 1 clock cycle
{
    dut->clk = 0;
    dut->eval(); // recompute w clk LO (nothing captures)
    dut->clk = 1;
    dut->eval(); // rising edge (clk 0->1) so eval sees t hat and fires always_ff @(posedge) blocks
}

static void reset(Vitch_parser* dut)
{
    dut->rst_n = 0;
    dut->s_axis_tvalid = 0;
    dut->s_axis_tdata = 0;
    dut->m_axis_tready = 1;

    for (int i = 0; i < RESET_CYCLES; i++) {
        tick(dut);
    }

    dut->rst_n = 1;
    tick(dut);
}

// ignores s_axis_tready for now - fix when backpressure test written
static void push_byte(Vitch_parser* dut, uint8_t b)
{
    dut->s_axis_tdata = b;
    dut->s_axis_tvalid = 1;
    tick(dut);
}

static void send_msg(Vitch_parser* dut, const uint8_t* msg, size_t len)
{
    for (size_t i = 0; i < len; i++) {
        push_byte(dut, msg[i]);
    }
}

static int wait_for_msg(Vitch_parser *dut, int max_cycles = 100)
{
    for (int i = 0; i < max_cycles; i++) {
        if (dut->m_axis_tvalid) {
            return i;
        }
        dut->s_axis_tvalid = 0;
        tick(dut);
    }
    return -1;
}

/*
word11:
rsvd0 (27b) - 383:357
is_buy (1b) - 356
msg_type (4b) - 355:352 

word10:
rsvd1 (16b) - 351:336
stock_locate - 335:320

word 9,8:
rsvd2 (16b) - 319:304
timestamp (48b) - 303:256

word 7,6:
order_ref (64b) - 255:192

word 5:
shares (32b) - 191:160

word 4,3:
stock (64b) - 159:96

word 2:
price (32b) - 95:64

word 1:
match_num (64b) - 63:0
*/

// extract from padding
static inline uint64_t get_match_num(Vitch_parser *dut) 
{
    return ((uint64_t)dut->m_axis_tdata[1] << 32) | dut->m_axis_tdata[0];
}
static inline uint32_t get_price(Vitch_parser *dut) 
{
    return dut->m_axis_tdata[2];
}
static inline uint64_t get_stock(Vitch_parser *dut) 
{
    return ((uint64_t)dut->m_axis_tdata[4] << 32) | dut->m_axis_tdata[3];
}
static inline uint32_t get_shares(Vitch_parser *dut) 
{
    return dut->m_axis_tdata[5];
}
static inline uint64_t get_order_ref(Vitch_parser *dut) 
{
    return ((uint64_t)dut->m_axis_tdata[7] << 32) | dut->m_axis_tdata[6];
}
static inline uint64_t get_timestamp(Vitch_parser *dut) 
{
    return ((uint64_t)dut->m_axis_tdata[9] << 32) | dut->m_axis_tdata[8];
}
static inline uint16_t get_locate(Vitch_parser *dut) 
{
    return (uint16_t)(dut->m_axis_tdata[10] & 0xFFFF);
}
static inline uint8_t get_msg_type(Vitch_parser *dut) 
{
    return (uint8_t)(dut->m_axis_tdata[11] & 0xF);
}
static inline bool get_is_buy(Vitch_parser *dut) 
{
    return (dut->m_axis_tdata[11] >> 4) & 1;
}

// enum values (matches msg_pkg)
static constexpr uint8_t MSG_NONE = 0;
static constexpr uint8_t MSG_ADD  = 1;
static constexpr uint8_t MSG_EXC  = 2;
static constexpr uint8_t MSG_DEL  = 3;

static int failures = 0;
static void check(uint64_t actual, uint64_t expected, const char* name)
{
    if (actual != expected) {
        std::printf("FAIL %-14s got: 0x%11x, expected: 0x%11x\n",
                    name, (unsigned long long)actual, (unsigned long long)expected);
        failures++;
    }
}

int main(int argc, char** argv)
{
    Verilated::commandArgs(argc, argv); // give args to the runtime
    Vitch_parser* dut = new Vitch_parser; // alloc'd (Device-Under-Test)

    reset(dut);

    // TESTING //
        AddOrder add;
        add.stock_locate  = 1;
        add.tracking_num  = 2;
        add.timestamp = 0x0A4E22819000ULL;
        add.order_ref_num = 0x38D;
        add.is_buy = true;
        add.shares = 300;
        add.stock = "APPL";
        add.price = 1234500;

        uint8_t msg[ADD_ORDER_LEN];
        build_add_order(msg, add);

        send_msg(dut, msg, ADD_ORDER_LEN);

        int waited = wait_for_msg(dut);
        if (waited < 0) {
            std::printf("FAILED (no message emitted within timeout period)");
            return 1;
        }

        std::printf("TEST: an add order\n");
        check(get_msg_type(dut), MSG_ADD, "msg_type");
        check(get_is_buy(dut), add.is_buy, "is_buy");
        check(get_locate(dut), add.stock_locate, "stock_locate");
        check(get_timestamp(dut), add.timestamp, "timestamp");
        check(get_order_ref(dut), add.order_ref_num, "order_ref_num");
        check(get_shares(dut), add.shares, "shares");
        check(get_stock(dut), ticker_to_u64(add.stock), "stock");
        check(get_price(dut), add.price, "price");

        std::printf("%s (failures: %d)\n", 
                    failures ? "FAILED" : "PASSED", failures);
    // TESTING //

    dut->final(); // tells Verilator simulation is over
    delete dut; // free()

    return failures ? 1 : 0;
}