/*
verilator --cc --exe --build -j 0 --top-module itch_parser \
    rtl/msg_pkg.sv rtl/skid_buffer.sv rtl/itch_parser.sv \
    tb/parser/tb_itch_parser.cpp
./obj_dir/Vitch_parser
*/

#include "Vitch_parser.h" // class generated by Verilator
#include <verilated.h> // runtime thing for Verilator
#include <cstdio>
#include <cstdint>

#include "../shared/itch_messages.hpp"

static constexpr int RESET_CYCLES = 5; // constexpr is C++ for eval this at compile time, not run time
static constexpr int TDATA_WORDS = 12; // 384b = 12 words * 32 bits

static void tick(Vitch_parser* dut) // 1 clock cycle
{
    dut->clk = 0;
    dut->eval(); // recompute w clk LO (nothing captures)
    dut->clk = 1;
    dut->eval(); // rising edge (clk 0->1) so eval sees t hat and fires always_ff @(posedge) blocks
}

static void reset(Vitch_parser* dut)
{
    dut->rst_n = 0;
    dut->s_axis_tvalid = 0;
    dut->s_axis_tdata = 0;
    dut->m_axis_tready = 1;

    for (int i = 0; i < RESET_CYCLES; i++) {
        tick(dut);
    }

    dut->rst_n = 1;
    tick(dut);
}

// ignores s_axis_tready for now - fix when backpressure test written
static void push_byte(Vitch_parser* dut, uint8_t b)
{
    dut->s_axis_tdata = b;
    dut->s_axis_tvalid = 1;
    tick(dut);
}

static void send_msg(Vitch_parser* dut, const uint8_t* msg, size_t len)
{
    for (size_t i = 0; i < len; i++) {
        push_byte(dut, msg[i]);
    }
}

static int wait_for_msg(Vitch_parser *dut, int max_cycles = 100)
{
    for (int i = 0; i < max_cycles; i++) {
        if (dut->m_axis_tvalid) {
            return i;
        }
        dut->s_axis_tvalid = 0;
        tick(dut);
    }
    return -1;
}

/*
word11:
rsvd0 (27b) - 383:357
is_buy (1b) - 356
msg_type (4b) - 355:352 

word10:
rsvd1 (16b) - 351:336
stock_locate - 335:320

word 9,8:
rsvd2 (16b) - 319:304
timestamp (48b) - 303:256

word 7,6:
order_ref (64b) - 255:192

word 5:
shares (32b) - 191:160

word 4,3:
stock (64b) - 159:96

word 2:
price (32b) - 95:64

word 1:
match_num (64b) - 63:0
*/

// extract from padding
static inline uint64_t get_match_num(Vitch_parser *dut) 
{
    return ((uint64_t)dut->m_axis_tdata[1] << 32) | dut->m_axis_tdata[0];
}
static inline uint32_t get_price(Vitch_parser *dut) 
{
    return dut->m_axis_tdata[2];
}
static inline uint64_t get_stock(Vitch_parser *dut) 
{
    return ((uint64_t)dut->m_axis_tdata[4] << 32) | dut->m_axis_tdata[3];
}
static inline uint32_t get_shares(Vitch_parser *dut) 
{
    return dut->m_axis_tdata[5];
}
static inline uint64_t get_order_ref(Vitch_parser *dut) 
{
    return ((uint64_t)dut->m_axis_tdata[7] << 32) | dut->m_axis_tdata[6];
}
static inline uint64_t get_timestamp(Vitch_parser *dut) 
{
    return ((uint64_t)dut->m_axis_tdata[9] << 32) | dut->m_axis_tdata[8];
}
static inline uint16_t get_locate(Vitch_parser *dut) 
{
    return (uint16_t)(dut->m_axis_tdata[10] & 0xFFFF);
}
static inline uint8_t get_msg_type(Vitch_parser *dut) 
{
    return (uint8_t)(dut->m_axis_tdata[11] & 0xF);
}
static inline bool get_is_buy(Vitch_parser *dut) 
{
    return (dut->m_axis_tdata[11] >> 4) & 1;
}

// enum values (matches msg_pkg)
static constexpr uint8_t MSG_NONE = 0;
static constexpr uint8_t MSG_ADD  = 1;
static constexpr uint8_t MSG_EXC  = 2;
static constexpr uint8_t MSG_DEL  = 3;

static int failures = 0;

static void check(uint64_t actual, uint64_t expected, const char* name)
{
    if (actual != expected) {
        std::printf("FAIL %-14s got: 0x%llx, expected: 0x%llx\n",
                    name, (unsigned long long)actual, (unsigned long long)expected);
        failures++;
    }
}

static void test_add_order(Vitch_parser *dut)
{
    std::printf("TESTING: Add Order (A)\n");
    reset(dut);

    OrderAdd add;
    add.stock_locate  = 1;
    add.tracking_num  = 1;
    add.timestamp = 1000;
    add.order_ref_num = 100;
    add.is_buy = true;
    add.shares = 500;
    add.stock = "AAPL";
    add.price = 1500000; // $150.0000

    uint8_t msg[ORDER_ADD_LEN];
    build_order_add(msg, add);
    send_msg(dut, msg, ORDER_ADD_LEN);

    int waited = wait_for_msg(dut);
    if (waited < 0) {
        std::printf("FAILED (no message emitted within timeout period)");
        failures++;
        return;
    }

    check(get_msg_type(dut), MSG_ADD, "msg_type");
    check(get_is_buy(dut), add.is_buy, "is_buy");
    check(get_locate(dut), add.stock_locate, "stock_locate");
    check(get_timestamp(dut), add.timestamp, "timestamp");
    check(get_order_ref(dut), add.order_ref_num, "order_ref_num");
    check(get_shares(dut), add.shares, "shares");
    check(get_stock(dut), ticker_to_u64(add.stock), "stock");
    check(get_price(dut), add.price, "price");
}

static void test_order_executed(Vitch_parser *dut)
{
    std::printf("TESTING: Order Executed (E)\n");
    reset(dut);

    OrderExecuted exc;
    exc.stock_locate = 1;
    exc.tracking_num  = 2;
    exc.timestamp = 2000;
    exc.order_ref_num = 100;
    exc.shares = 200;
    exc.match_num = 55;

    uint8_t msg[ORDER_EXECUTED_LEN];
    build_order_executed(msg, exc);
    send_msg(dut, msg, ORDER_EXECUTED_LEN);

    int waited = wait_for_msg(dut);
    if (waited < 0) {
        std::printf("FAILED (no message emitted within timeout period)");
        failures++;
        return;
    }

    check(get_msg_type(dut), MSG_EXC, "msg_type");
    check(get_locate(dut), exc.stock_locate, "stock_locate");
    check(get_timestamp(dut), exc.timestamp, "timestamp");
    check(get_order_ref(dut), exc.order_ref_num, "order_ref_num");
    check(get_shares(dut), exc.shares, "shares");
    check(get_match_num(dut), exc.match_num, "match_num");
}

static void test_order_delete(Vitch_parser *dut)
{
    std::printf("TESTING: Order Delete (D)\n");
    reset(dut);

    OrderDelete del;
    del.stock_locate = 1;
    del.tracking_num  = 3;
    del.timestamp = 3000;
    del.order_ref_num = 100;

    uint8_t msg[ORDER_DELETE_LEN];
    build_order_delete(msg, del);
    send_msg(dut, msg, ORDER_DELETE_LEN);

    int waited = wait_for_msg(dut);
    if (waited < 0) {
        std::printf("FAILED (no message emitted within timeout period)");
        failures++;
        return;
    }

    check(get_msg_type(dut), MSG_DEL, "msg_type");
    check(get_locate(dut), del.stock_locate, "stock_locate");
    check(get_timestamp(dut), del.timestamp, "timestamp");
    check(get_order_ref(dut), del.order_ref_num, "order_ref_num");
}

static void test_back2back(Vitch_parser *dut)
{
    std::printf("TESTING: Back to back stream (A -> E -> D)\n");
    reset(dut);

    OrderAdd add;
    add.stock_locate = 1;
    add.tracking_num = 1;
    add.timestamp = 1000;
    add.order_ref_num = 100;
    add.is_buy = false;
    add.shares = 500;
    add.stock = "MSFT";
    add.price = 1500000;

    OrderExecuted exc;
    exc.stock_locate = 1;
    exc.tracking_num = 2;
    exc.timestamp = 2000;
    exc.order_ref_num = 100;
    exc.shares = 200;
    exc.match_num = 55;

    OrderDelete del;
    del.stock_locate = 1;
    del.tracking_num = 3;
    del.timestamp = 3000;
    del.order_ref_num = 100;

    uint8_t stream[ORDER_ADD_LEN+ORDER_EXECUTED_LEN+ORDER_DELETE_LEN];
    build_order_add(&stream[0], add);
    build_order_executed(&stream[ORDER_ADD_LEN], exc);
    build_order_delete(&stream[ORDER_ADD_LEN+ORDER_EXECUTED_LEN], del);

    // To remember what came out
    struct CapturedMsg{
        uint8_t msg_type;
        uint64_t order_ref;
        uint32_t shares;
    };
    CapturedMsg captured[3]; //1 slot per msg we expect
    int num_captured = 0;

    for (size_t i = 0; i < sizeof(stream); i++){
        push_byte(dut, stream[i]);

        if (dut->m_axis_tvalid && num_captured<3){
            captured[num_captured].msg_type = get_msg_type(dut);
            captured[num_captured].order_ref = get_order_ref(dut);
            captured[num_captured].shares = get_shares(dut);
            num_captured++;
        }
    }

    // when final byte goes in, 3rd msg hasnt come out yet so we need 1 more cycle for the skid buffer
    // this ticks a few times w no input
    for (int i = 0; i < 5 && num_captured<3; i++){
        dut->s_axis_tvalid = 0; // no bytes left
        tick(dut);

        if (dut->m_axis_tvalid && num_captured<3){
            captured[num_captured].msg_type = get_msg_type(dut);
            captured[num_captured].order_ref = get_order_ref(dut);
            captured[num_captured].shares = get_shares(dut);
            num_captured++;
        }
    }

    check(num_captured, 3, "message count");
    if (num_captured != 3) return;

    check(captured[0].msg_type, MSG_ADD, "msg0type");
    check(captured[0].order_ref, add.order_ref_num, "msg0order_ref");
    check(captured[0].shares, add.shares, "msg0shares");

    check(captured[1].msg_type, MSG_EXC, "msg1type");
    check(captured[1].order_ref, exc.order_ref_num, "msg1order_ref");
    check(captured[1].shares, exc.shares, "msg1shares");

    check(captured[2].msg_type, MSG_DEL, "msg2type");
    check(captured[2].order_ref, del.order_ref_num, "msg2order_ref");
}


int main(int argc, char** argv) // (argument count (words typed), argument vector (words themselves))
{
    Verilated::commandArgs(argc, argv); // give args to the runtime
    Vitch_parser* dut = new Vitch_parser; // alloc'd (Device-Under-Test)

    test_add_order(dut);
    test_order_executed(dut);
    test_order_delete(dut);
    test_back2back(dut);

    std::printf("\n%s (Failures: %d)\n",
                failures ? "FAILED" : "PASSED", failures);
    
    dut->final(); // tells Verilator simulation is over
    delete dut; // free()

    return failures ? 1 : 0;
}